# Generated by Django 3.1.4 on 2021-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('RepositoryID', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('RepositoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('SettingID', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
