# Generated by Django 3.1.4 on 2021-02-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='ImportedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repositories',
            name='RepositoryBaseDir',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='SettingKey',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='SettingValue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repositories',
            name='RepositoryName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
