# Generated by Django 3.1.4 on 2021-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210225_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='LastIndexed',
            field=models.DateTimeField(null=True),
        ),
    ]
