# Generated by Django 3.1.4 on 2021-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_repositories_lastindexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='RepositoryID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='SettingID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
