# Generated by Django 3.1.7 on 2021-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210330_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.UUIDField(primary_key=True, serialize=False)),
                ('RepositoryID', models.UUIDField()),
                ('Filename', models.CharField(max_length=255, null=True)),
                ('FilePath', models.TextField(null=True)),
                ('DateAdded', models.DateTimeField(null=True)),
            ],
        ),
    ]
